######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 26 20:32:39 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += console

# Input
HEADERS += QPythonConsole.h
SOURCES += main.cc QPythonConsole.cc
