#!/usr/bin/env python

import sys
fn = 'puzzle1.in' if len(sys.argv) == 1 else sys.argv[1]

N = int(open(fn).read())
for i in xrange(1, N+1):
    if not i % 3 and not i % 5: print 'Hop'
    elif not i % 3: print 'Hoppity'
    elif not i % 5: print 'Hophop'
