#!/usr/bin/env python
# vim:set tabstop=4 shiftwidth=4 expandtab:
from collections import defaultdict

import sys
fn = 'in' if len(sys.argv) == 1 else sys.argv[1]

debug = False

people_say_cnt = defaultdict(int)
people_say = defaultdict(list)

lines = open(fn).read().splitlines()
N = int(lines[0])
j = 1
for i in xrange(N):
    people, nb_liar = lines[j].split()
    nb_liar = int(nb_liar)

    for liar in lines[j+1:j+1+nb_liar]:
        people_say_cnt[liar] += 1
        people_say[people].append(liar)

    j += 1 + nb_liar

if debug: print people_say
if debug: print people_say_cnt

liars_for_sure = [k for k, v in people_say_cnt.iteritems() if v > 1]

if debug: print liars_for_sure

for liar in liars_for_sure:
    if debug: print liar, 'lied about', people_say[liar]
    for people in people_say[liar]:
        people_say_cnt[people] -= 1

if debug: print people_say_cnt
liars = [k for k, v in people_say_cnt.iteritems() if v >= 1]

nb_liars = len(liars)
good_peoples = N - nb_liars

if good_peoples > nb_liars:
    print good_peoples, nb_liars
else:
    print nb_liars, good_peoples
