######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 11 23:09:26 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += RadialDiskView.h
SOURCES += main.cc RadialDiskView.cc
